// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User_Gender int32

const (
	User_UNKNOWN User_Gender = 0
	User_MALE    User_Gender = 1
	User_FEMALE  User_Gender = 2
)

var User_Gender_name = map[int32]string{
	0: "UNKNOWN",
	1: "MALE",
	2: "FEMALE",
}

var User_Gender_value = map[string]int32{
	"UNKNOWN": 0,
	"MALE":    1,
	"FEMALE":  2,
}

func (x User_Gender) String() string {
	return proto.EnumName(User_Gender_name, int32(x))
}

func (User_Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7965fb6944d08275, []int{0, 0}
}

type User struct {
	UserID               uint32      `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	UserName             string      `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	UserEmail            string      `protobuf:"bytes,3,opt,name=userEmail,proto3" json:"userEmail,omitempty"`
	Gender               User_Gender `protobuf:"varint,4,opt,name=gender,proto3,enum=user.User_Gender" json:"gender,omitempty"`
	Age                  uint32      `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_7965fb6944d08275, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetUserEmail() string {
	if m != nil {
		return m.UserEmail
	}
	return ""
}

func (m *User) GetGender() User_Gender {
	if m != nil {
		return m.Gender
	}
	return User_UNKNOWN
}

func (m *User) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterEnum("user.User_Gender", User_Gender_name, User_Gender_value)
	proto.RegisterType((*User)(nil), "user.User")
}

func init() {
	proto.RegisterFile("user_message.proto", fileDescriptor_7965fb6944d08275)
}

var fileDescriptor_7965fb6944d08275 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x2d, 0x4e, 0x2d,
	0x8a, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x01, 0x89, 0x29, 0x1d, 0x62, 0xe4, 0x62, 0x09, 0x05, 0x32, 0x84, 0xc4, 0xb8, 0xd8, 0x40, 0x02,
	0x9e, 0x2e, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xbc, 0x41, 0x50, 0x9e, 0x90, 0x14, 0x17, 0x07, 0x88,
	0xe5, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0x04, 0x94, 0xe1, 0x0c, 0x82, 0xf3, 0x85, 0x64, 0xb8, 0x38,
	0x41, 0x6c, 0xd7, 0xdc, 0xc4, 0xcc, 0x1c, 0x09, 0x66, 0xb0, 0x24, 0x42, 0x40, 0x48, 0x93, 0x8b,
	0x2d, 0x3d, 0x35, 0x2f, 0x25, 0xb5, 0x48, 0x82, 0x05, 0x28, 0xc5, 0x67, 0x24, 0xa8, 0x07, 0x92,
	0xd3, 0x03, 0xd9, 0xa6, 0xe7, 0x0e, 0x96, 0x08, 0x82, 0x2a, 0x10, 0x12, 0xe0, 0x62, 0x06, 0x3a,
	0x4c, 0x82, 0x15, 0x6c, 0x33, 0x88, 0xa9, 0xa4, 0xcd, 0xc5, 0x06, 0x51, 0x23, 0xc4, 0xcd, 0xc5,
	0x1e, 0xea, 0xe7, 0xed, 0xe7, 0x1f, 0xee, 0x27, 0xc0, 0x20, 0xc4, 0xc1, 0xc5, 0xe2, 0xeb, 0xe8,
	0xe3, 0x2a, 0xc0, 0x28, 0xc4, 0xc5, 0xc5, 0xe6, 0xe6, 0x0a, 0x66, 0x33, 0x39, 0xb1, 0x44, 0x31,
	0x15, 0x24, 0x25, 0xb1, 0x81, 0xfd, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x80, 0xa4, 0xdf,
	0x8f, 0xed, 0x00, 0x00, 0x00,
}
